#!/bin/bash

# compute project directory locations
projectdir="$(pwd)/$(dirname $0)/.."

# initialize instance variables
classpath="$projectdir/build/libs/eebulk-cli-0.1.2-all.jar"
javaopts="-Xmx2G -Dorg.slf4j.simpleLogger.defaultLogLevel=debug"
mainclass="io.blackpine.eebulk.Main"

#javaopts="$javaopts -Djavax.net.debug=ssl,keymanager"

# start application
java -cp $classpath $javaopts $mainclass $@
