#!/bin/bash
APPLICATION="eebulk-cli"
VERSION="0.1.0"

CLASSPATH=""
BASEDIR=$(dirname $0)
HOSTNAME=$(hostname)
if [ -f $BASEDIR/build/libs/$APPLICATION-$VERSION.jar ]; then
    CLASSPATH="$BASEDIR/build/libs/$APPLICATION-$VERSION.jar"
else
    echo "unable to find $APPLICATION-$VERSION.jar."
    exit 1
fi

JAVA_OPTS="-Xmx2G"

java -cp $CLASSPATH $JAVA_OPTS io.blackpine.eebulk.Main $@
